import "./globals.css";
import type { Metadata } from "next";

import ReduxProvide from "@/providers/ReduxProvider";
import { NextUiProviders } from "../providers/NextUiProvider";
import NavbarFrame from "@/components/ui/Navbar/Navbar";
import ApiHitProvide from "@/providers/ApiHitLayout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body>
				<ReduxProvide>
					<NextUiProviders>
						<ApiHitProvide>
							<NavbarFrame />
							{children}
						</ApiHitProvide>
					</NextUiProviders>
				</ReduxProvide>
			</body>
		</html>
	);
}
